spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: proxy-reverso-api
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi